#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DatPhongKhachSan")]
	public partial class QL_KhachSanDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCT_PDP_DV(CT_PDP_DV instance);
    partial void UpdateCT_PDP_DV(CT_PDP_DV instance);
    partial void DeleteCT_PDP_DV(CT_PDP_DV instance);
    partial void InsertDich_Vu(Dich_Vu instance);
    partial void UpdateDich_Vu(Dich_Vu instance);
    partial void DeleteDich_Vu(Dich_Vu instance);
    partial void InsertDM_Man_Hinh(DM_Man_Hinh instance);
    partial void UpdateDM_Man_Hinh(DM_Man_Hinh instance);
    partial void DeleteDM_Man_Hinh(DM_Man_Hinh instance);
    partial void InsertHinh_Anh_Phong(Hinh_Anh_Phong instance);
    partial void UpdateHinh_Anh_Phong(Hinh_Anh_Phong instance);
    partial void DeleteHinh_Anh_Phong(Hinh_Anh_Phong instance);
    partial void InsertKhach_Hang(Khach_Hang instance);
    partial void UpdateKhach_Hang(Khach_Hang instance);
    partial void DeleteKhach_Hang(Khach_Hang instance);
    partial void InsertLoai_Phong(Loai_Phong instance);
    partial void UpdateLoai_Phong(Loai_Phong instance);
    partial void DeleteLoai_Phong(Loai_Phong instance);
    partial void InsertNhom_Nguoi_Dung(Nhom_Nguoi_Dung instance);
    partial void UpdateNhom_Nguoi_Dung(Nhom_Nguoi_Dung instance);
    partial void DeleteNhom_Nguoi_Dung(Nhom_Nguoi_Dung instance);
    partial void InsertPhan_Quyen(Phan_Quyen instance);
    partial void UpdatePhan_Quyen(Phan_Quyen instance);
    partial void DeletePhan_Quyen(Phan_Quyen instance);
    partial void InsertPhieu_Dat_Phong(Phieu_Dat_Phong instance);
    partial void UpdatePhieu_Dat_Phong(Phieu_Dat_Phong instance);
    partial void DeletePhieu_Dat_Phong(Phieu_Dat_Phong instance);
    partial void InsertPhong(Phong instance);
    partial void UpdatePhong(Phong instance);
    partial void DeletePhong(Phong instance);
    #endregion
		
		public QL_KhachSanDataContext() : 
				base(global::DAL.Properties.Settings.Default.DatPhongKhachSanConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QL_KhachSanDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QL_KhachSanDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QL_KhachSanDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QL_KhachSanDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CT_PDP_DV> CT_PDP_DVs
		{
			get
			{
				return this.GetTable<CT_PDP_DV>();
			}
		}
		
		public System.Data.Linq.Table<Dich_Vu> Dich_Vus
		{
			get
			{
				return this.GetTable<Dich_Vu>();
			}
		}
		
		public System.Data.Linq.Table<DM_Man_Hinh> DM_Man_Hinhs
		{
			get
			{
				return this.GetTable<DM_Man_Hinh>();
			}
		}
		
		public System.Data.Linq.Table<Hinh_Anh_Phong> Hinh_Anh_Phongs
		{
			get
			{
				return this.GetTable<Hinh_Anh_Phong>();
			}
		}
		
		public System.Data.Linq.Table<Khach_Hang> Khach_Hangs
		{
			get
			{
				return this.GetTable<Khach_Hang>();
			}
		}
		
		public System.Data.Linq.Table<Loai_Phong> Loai_Phongs
		{
			get
			{
				return this.GetTable<Loai_Phong>();
			}
		}
		
		public System.Data.Linq.Table<Nhom_Nguoi_Dung> Nhom_Nguoi_Dungs
		{
			get
			{
				return this.GetTable<Nhom_Nguoi_Dung>();
			}
		}
		
		public System.Data.Linq.Table<Phan_Quyen> Phan_Quyens
		{
			get
			{
				return this.GetTable<Phan_Quyen>();
			}
		}
		
		public System.Data.Linq.Table<Phieu_Dat_Phong> Phieu_Dat_Phongs
		{
			get
			{
				return this.GetTable<Phieu_Dat_Phong>();
			}
		}
		
		public System.Data.Linq.Table<Phong> Phongs
		{
			get
			{
				return this.GetTable<Phong>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CT_PDP_DV")]
	public partial class CT_PDP_DV : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maDatPhong;
		
		private int _maDichVu;
		
		private System.Nullable<int> _soLuong;
		
		private System.Nullable<decimal> _tongTien;
		
		private EntityRef<Dich_Vu> _Dich_Vu;
		
		private EntityRef<Phieu_Dat_Phong> _Phieu_Dat_Phong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaDatPhongChanging(int value);
    partial void OnmaDatPhongChanged();
    partial void OnmaDichVuChanging(int value);
    partial void OnmaDichVuChanged();
    partial void OnsoLuongChanging(System.Nullable<int> value);
    partial void OnsoLuongChanged();
    partial void OntongTienChanging(System.Nullable<decimal> value);
    partial void OntongTienChanged();
    #endregion
		
		public CT_PDP_DV()
		{
			this._Dich_Vu = default(EntityRef<Dich_Vu>);
			this._Phieu_Dat_Phong = default(EntityRef<Phieu_Dat_Phong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maDatPhong", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int maDatPhong
		{
			get
			{
				return this._maDatPhong;
			}
			set
			{
				if ((this._maDatPhong != value))
				{
					if (this._Phieu_Dat_Phong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaDatPhongChanging(value);
					this.SendPropertyChanging();
					this._maDatPhong = value;
					this.SendPropertyChanged("maDatPhong");
					this.OnmaDatPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maDichVu", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int maDichVu
		{
			get
			{
				return this._maDichVu;
			}
			set
			{
				if ((this._maDichVu != value))
				{
					if (this._Dich_Vu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaDichVuChanging(value);
					this.SendPropertyChanging();
					this._maDichVu = value;
					this.SendPropertyChanged("maDichVu");
					this.OnmaDichVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuong", DbType="Int")]
		public System.Nullable<int> soLuong
		{
			get
			{
				return this._soLuong;
			}
			set
			{
				if ((this._soLuong != value))
				{
					this.OnsoLuongChanging(value);
					this.SendPropertyChanging();
					this._soLuong = value;
					this.SendPropertyChanged("soLuong");
					this.OnsoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongTien", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> tongTien
		{
			get
			{
				return this._tongTien;
			}
			set
			{
				if ((this._tongTien != value))
				{
					this.OntongTienChanging(value);
					this.SendPropertyChanging();
					this._tongTien = value;
					this.SendPropertyChanged("tongTien");
					this.OntongTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dich_Vu_CT_PDP_DV", Storage="_Dich_Vu", ThisKey="maDichVu", OtherKey="maDichVu", IsForeignKey=true)]
		public Dich_Vu Dich_Vu
		{
			get
			{
				return this._Dich_Vu.Entity;
			}
			set
			{
				Dich_Vu previousValue = this._Dich_Vu.Entity;
				if (((previousValue != value) 
							|| (this._Dich_Vu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Dich_Vu.Entity = null;
						previousValue.CT_PDP_DVs.Remove(this);
					}
					this._Dich_Vu.Entity = value;
					if ((value != null))
					{
						value.CT_PDP_DVs.Add(this);
						this._maDichVu = value.maDichVu;
					}
					else
					{
						this._maDichVu = default(int);
					}
					this.SendPropertyChanged("Dich_Vu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phieu_Dat_Phong_CT_PDP_DV", Storage="_Phieu_Dat_Phong", ThisKey="maDatPhong", OtherKey="maDatPhong", IsForeignKey=true)]
		public Phieu_Dat_Phong Phieu_Dat_Phong
		{
			get
			{
				return this._Phieu_Dat_Phong.Entity;
			}
			set
			{
				Phieu_Dat_Phong previousValue = this._Phieu_Dat_Phong.Entity;
				if (((previousValue != value) 
							|| (this._Phieu_Dat_Phong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Phieu_Dat_Phong.Entity = null;
						previousValue.CT_PDP_DVs.Remove(this);
					}
					this._Phieu_Dat_Phong.Entity = value;
					if ((value != null))
					{
						value.CT_PDP_DVs.Add(this);
						this._maDatPhong = value.maDatPhong;
					}
					else
					{
						this._maDatPhong = default(int);
					}
					this.SendPropertyChanged("Phieu_Dat_Phong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Dich_Vu")]
	public partial class Dich_Vu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maDichVu;
		
		private string _tenDich;
		
		private string _acronym;
		
		private System.Nullable<decimal> _donGia;
		
		private EntitySet<CT_PDP_DV> _CT_PDP_DVs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaDichVuChanging(int value);
    partial void OnmaDichVuChanged();
    partial void OntenDichChanging(string value);
    partial void OntenDichChanged();
    partial void OnacronymChanging(string value);
    partial void OnacronymChanged();
    partial void OndonGiaChanging(System.Nullable<decimal> value);
    partial void OndonGiaChanged();
    #endregion
		
		public Dich_Vu()
		{
			this._CT_PDP_DVs = new EntitySet<CT_PDP_DV>(new Action<CT_PDP_DV>(this.attach_CT_PDP_DVs), new Action<CT_PDP_DV>(this.detach_CT_PDP_DVs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maDichVu", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maDichVu
		{
			get
			{
				return this._maDichVu;
			}
			set
			{
				if ((this._maDichVu != value))
				{
					this.OnmaDichVuChanging(value);
					this.SendPropertyChanging();
					this._maDichVu = value;
					this.SendPropertyChanged("maDichVu");
					this.OnmaDichVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenDich", DbType="VarChar(100)")]
		public string tenDich
		{
			get
			{
				return this._tenDich;
			}
			set
			{
				if ((this._tenDich != value))
				{
					this.OntenDichChanging(value);
					this.SendPropertyChanging();
					this._tenDich = value;
					this.SendPropertyChanged("tenDich");
					this.OntenDichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_acronym", DbType="VarChar(10)")]
		public string acronym
		{
			get
			{
				return this._acronym;
			}
			set
			{
				if ((this._acronym != value))
				{
					this.OnacronymChanging(value);
					this.SendPropertyChanging();
					this._acronym = value;
					this.SendPropertyChanged("acronym");
					this.OnacronymChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_donGia", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> donGia
		{
			get
			{
				return this._donGia;
			}
			set
			{
				if ((this._donGia != value))
				{
					this.OndonGiaChanging(value);
					this.SendPropertyChanging();
					this._donGia = value;
					this.SendPropertyChanged("donGia");
					this.OndonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dich_Vu_CT_PDP_DV", Storage="_CT_PDP_DVs", ThisKey="maDichVu", OtherKey="maDichVu")]
		public EntitySet<CT_PDP_DV> CT_PDP_DVs
		{
			get
			{
				return this._CT_PDP_DVs;
			}
			set
			{
				this._CT_PDP_DVs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CT_PDP_DVs(CT_PDP_DV entity)
		{
			this.SendPropertyChanging();
			entity.Dich_Vu = this;
		}
		
		private void detach_CT_PDP_DVs(CT_PDP_DV entity)
		{
			this.SendPropertyChanging();
			entity.Dich_Vu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DM_Man_Hinh")]
	public partial class DM_Man_Hinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maManHinh;
		
		private string _tenManHinh;
		
		private EntitySet<Phan_Quyen> _Phan_Quyens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaManHinhChanging(int value);
    partial void OnmaManHinhChanged();
    partial void OntenManHinhChanging(string value);
    partial void OntenManHinhChanged();
    #endregion
		
		public DM_Man_Hinh()
		{
			this._Phan_Quyens = new EntitySet<Phan_Quyen>(new Action<Phan_Quyen>(this.attach_Phan_Quyens), new Action<Phan_Quyen>(this.detach_Phan_Quyens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maManHinh", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maManHinh
		{
			get
			{
				return this._maManHinh;
			}
			set
			{
				if ((this._maManHinh != value))
				{
					this.OnmaManHinhChanging(value);
					this.SendPropertyChanging();
					this._maManHinh = value;
					this.SendPropertyChanged("maManHinh");
					this.OnmaManHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenManHinh", DbType="VarChar(100)")]
		public string tenManHinh
		{
			get
			{
				return this._tenManHinh;
			}
			set
			{
				if ((this._tenManHinh != value))
				{
					this.OntenManHinhChanging(value);
					this.SendPropertyChanging();
					this._tenManHinh = value;
					this.SendPropertyChanged("tenManHinh");
					this.OntenManHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DM_Man_Hinh_Phan_Quyen", Storage="_Phan_Quyens", ThisKey="maManHinh", OtherKey="maManHinh")]
		public EntitySet<Phan_Quyen> Phan_Quyens
		{
			get
			{
				return this._Phan_Quyens;
			}
			set
			{
				this._Phan_Quyens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Phan_Quyens(Phan_Quyen entity)
		{
			this.SendPropertyChanging();
			entity.DM_Man_Hinh = this;
		}
		
		private void detach_Phan_Quyens(Phan_Quyen entity)
		{
			this.SendPropertyChanging();
			entity.DM_Man_Hinh = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Hinh_Anh_Phong")]
	public partial class Hinh_Anh_Phong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maHinhAnh;
		
		private string _url;
		
		private System.Nullable<int> _maPhong;
		
		private EntityRef<Phong> _Phong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaHinhAnhChanging(int value);
    partial void OnmaHinhAnhChanged();
    partial void OnurlChanging(string value);
    partial void OnurlChanged();
    partial void OnmaPhongChanging(System.Nullable<int> value);
    partial void OnmaPhongChanged();
    #endregion
		
		public Hinh_Anh_Phong()
		{
			this._Phong = default(EntityRef<Phong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHinhAnh", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maHinhAnh
		{
			get
			{
				return this._maHinhAnh;
			}
			set
			{
				if ((this._maHinhAnh != value))
				{
					this.OnmaHinhAnhChanging(value);
					this.SendPropertyChanging();
					this._maHinhAnh = value;
					this.SendPropertyChanged("maHinhAnh");
					this.OnmaHinhAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_url", DbType="VarChar(255)")]
		public string url
		{
			get
			{
				return this._url;
			}
			set
			{
				if ((this._url != value))
				{
					this.OnurlChanging(value);
					this.SendPropertyChanging();
					this._url = value;
					this.SendPropertyChanged("url");
					this.OnurlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maPhong", DbType="Int")]
		public System.Nullable<int> maPhong
		{
			get
			{
				return this._maPhong;
			}
			set
			{
				if ((this._maPhong != value))
				{
					if (this._Phong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaPhongChanging(value);
					this.SendPropertyChanging();
					this._maPhong = value;
					this.SendPropertyChanged("maPhong");
					this.OnmaPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phong_Hinh_Anh_Phong", Storage="_Phong", ThisKey="maPhong", OtherKey="maPhong", IsForeignKey=true)]
		public Phong Phong
		{
			get
			{
				return this._Phong.Entity;
			}
			set
			{
				Phong previousValue = this._Phong.Entity;
				if (((previousValue != value) 
							|| (this._Phong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Phong.Entity = null;
						previousValue.Hinh_Anh_Phongs.Remove(this);
					}
					this._Phong.Entity = value;
					if ((value != null))
					{
						value.Hinh_Anh_Phongs.Add(this);
						this._maPhong = value.maPhong;
					}
					else
					{
						this._maPhong = default(Nullable<int>);
					}
					this.SendPropertyChanged("Phong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Khach_Hang")]
	public partial class Khach_Hang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maKH;
		
		private string _userName;
		
		private string _password;
		
		private string _hoTen;
		
		private string _email;
		
		private string _diaChi;
		
		private string _soDienThoai;
		
		private System.Nullable<int> _maNhomNguoiDung;
		
		private EntitySet<Phieu_Dat_Phong> _Phieu_Dat_Phongs;
		
		private EntityRef<Nhom_Nguoi_Dung> _Nhom_Nguoi_Dung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaKHChanging(int value);
    partial void OnmaKHChanged();
    partial void OnuserNameChanging(string value);
    partial void OnuserNameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnhoTenChanging(string value);
    partial void OnhoTenChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OndiaChiChanging(string value);
    partial void OndiaChiChanged();
    partial void OnsoDienThoaiChanging(string value);
    partial void OnsoDienThoaiChanged();
    partial void OnmaNhomNguoiDungChanging(System.Nullable<int> value);
    partial void OnmaNhomNguoiDungChanged();
    #endregion
		
		public Khach_Hang()
		{
			this._Phieu_Dat_Phongs = new EntitySet<Phieu_Dat_Phong>(new Action<Phieu_Dat_Phong>(this.attach_Phieu_Dat_Phongs), new Action<Phieu_Dat_Phong>(this.detach_Phieu_Dat_Phongs));
			this._Nhom_Nguoi_Dung = default(EntityRef<Nhom_Nguoi_Dung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maKH
		{
			get
			{
				return this._maKH;
			}
			set
			{
				if ((this._maKH != value))
				{
					this.OnmaKHChanging(value);
					this.SendPropertyChanging();
					this._maKH = value;
					this.SendPropertyChanged("maKH");
					this.OnmaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string userName
		{
			get
			{
				return this._userName;
			}
			set
			{
				if ((this._userName != value))
				{
					this.OnuserNameChanging(value);
					this.SendPropertyChanging();
					this._userName = value;
					this.SendPropertyChanged("userName");
					this.OnuserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoTen", DbType="VarChar(100)")]
		public string hoTen
		{
			get
			{
				return this._hoTen;
			}
			set
			{
				if ((this._hoTen != value))
				{
					this.OnhoTenChanging(value);
					this.SendPropertyChanging();
					this._hoTen = value;
					this.SendPropertyChanged("hoTen");
					this.OnhoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChi", DbType="VarChar(255)")]
		public string diaChi
		{
			get
			{
				return this._diaChi;
			}
			set
			{
				if ((this._diaChi != value))
				{
					this.OndiaChiChanging(value);
					this.SendPropertyChanging();
					this._diaChi = value;
					this.SendPropertyChanged("diaChi");
					this.OndiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soDienThoai", DbType="VarChar(20)")]
		public string soDienThoai
		{
			get
			{
				return this._soDienThoai;
			}
			set
			{
				if ((this._soDienThoai != value))
				{
					this.OnsoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._soDienThoai = value;
					this.SendPropertyChanged("soDienThoai");
					this.OnsoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhomNguoiDung", DbType="Int")]
		public System.Nullable<int> maNhomNguoiDung
		{
			get
			{
				return this._maNhomNguoiDung;
			}
			set
			{
				if ((this._maNhomNguoiDung != value))
				{
					if (this._Nhom_Nguoi_Dung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNhomNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._maNhomNguoiDung = value;
					this.SendPropertyChanged("maNhomNguoiDung");
					this.OnmaNhomNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khach_Hang_Phieu_Dat_Phong", Storage="_Phieu_Dat_Phongs", ThisKey="maKH", OtherKey="maKH")]
		public EntitySet<Phieu_Dat_Phong> Phieu_Dat_Phongs
		{
			get
			{
				return this._Phieu_Dat_Phongs;
			}
			set
			{
				this._Phieu_Dat_Phongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nhom_Nguoi_Dung_Khach_Hang", Storage="_Nhom_Nguoi_Dung", ThisKey="maNhomNguoiDung", OtherKey="maNhom", IsForeignKey=true)]
		public Nhom_Nguoi_Dung Nhom_Nguoi_Dung
		{
			get
			{
				return this._Nhom_Nguoi_Dung.Entity;
			}
			set
			{
				Nhom_Nguoi_Dung previousValue = this._Nhom_Nguoi_Dung.Entity;
				if (((previousValue != value) 
							|| (this._Nhom_Nguoi_Dung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Nhom_Nguoi_Dung.Entity = null;
						previousValue.Khach_Hangs.Remove(this);
					}
					this._Nhom_Nguoi_Dung.Entity = value;
					if ((value != null))
					{
						value.Khach_Hangs.Add(this);
						this._maNhomNguoiDung = value.maNhom;
					}
					else
					{
						this._maNhomNguoiDung = default(Nullable<int>);
					}
					this.SendPropertyChanged("Nhom_Nguoi_Dung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Phieu_Dat_Phongs(Phieu_Dat_Phong entity)
		{
			this.SendPropertyChanging();
			entity.Khach_Hang = this;
		}
		
		private void detach_Phieu_Dat_Phongs(Phieu_Dat_Phong entity)
		{
			this.SendPropertyChanging();
			entity.Khach_Hang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Loai_Phong")]
	public partial class Loai_Phong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maLoaiPhong;
		
		private string _tenLoaiPhong;
		
		private string _moTa;
		
		private EntitySet<Phong> _Phongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaLoaiPhongChanging(int value);
    partial void OnmaLoaiPhongChanged();
    partial void OntenLoaiPhongChanging(string value);
    partial void OntenLoaiPhongChanged();
    partial void OnmoTaChanging(string value);
    partial void OnmoTaChanged();
    #endregion
		
		public Loai_Phong()
		{
			this._Phongs = new EntitySet<Phong>(new Action<Phong>(this.attach_Phongs), new Action<Phong>(this.detach_Phongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLoaiPhong", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maLoaiPhong
		{
			get
			{
				return this._maLoaiPhong;
			}
			set
			{
				if ((this._maLoaiPhong != value))
				{
					this.OnmaLoaiPhongChanging(value);
					this.SendPropertyChanging();
					this._maLoaiPhong = value;
					this.SendPropertyChanged("maLoaiPhong");
					this.OnmaLoaiPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenLoaiPhong", DbType="VarChar(100)")]
		public string tenLoaiPhong
		{
			get
			{
				return this._tenLoaiPhong;
			}
			set
			{
				if ((this._tenLoaiPhong != value))
				{
					this.OntenLoaiPhongChanging(value);
					this.SendPropertyChanging();
					this._tenLoaiPhong = value;
					this.SendPropertyChanged("tenLoaiPhong");
					this.OntenLoaiPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_moTa", DbType="VarChar(250)")]
		public string moTa
		{
			get
			{
				return this._moTa;
			}
			set
			{
				if ((this._moTa != value))
				{
					this.OnmoTaChanging(value);
					this.SendPropertyChanging();
					this._moTa = value;
					this.SendPropertyChanged("moTa");
					this.OnmoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Loai_Phong_Phong", Storage="_Phongs", ThisKey="maLoaiPhong", OtherKey="maLoaiPhong")]
		public EntitySet<Phong> Phongs
		{
			get
			{
				return this._Phongs;
			}
			set
			{
				this._Phongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Phongs(Phong entity)
		{
			this.SendPropertyChanging();
			entity.Loai_Phong = this;
		}
		
		private void detach_Phongs(Phong entity)
		{
			this.SendPropertyChanging();
			entity.Loai_Phong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Nhom_Nguoi_Dung")]
	public partial class Nhom_Nguoi_Dung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maNhom;
		
		private string _tenNhom;
		
		private string _ghiChu;
		
		private EntitySet<Khach_Hang> _Khach_Hangs;
		
		private EntitySet<Phan_Quyen> _Phan_Quyens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaNhomChanging(int value);
    partial void OnmaNhomChanged();
    partial void OntenNhomChanging(string value);
    partial void OntenNhomChanged();
    partial void OnghiChuChanging(string value);
    partial void OnghiChuChanged();
    #endregion
		
		public Nhom_Nguoi_Dung()
		{
			this._Khach_Hangs = new EntitySet<Khach_Hang>(new Action<Khach_Hang>(this.attach_Khach_Hangs), new Action<Khach_Hang>(this.detach_Khach_Hangs));
			this._Phan_Quyens = new EntitySet<Phan_Quyen>(new Action<Phan_Quyen>(this.attach_Phan_Quyens), new Action<Phan_Quyen>(this.detach_Phan_Quyens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhom", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maNhom
		{
			get
			{
				return this._maNhom;
			}
			set
			{
				if ((this._maNhom != value))
				{
					this.OnmaNhomChanging(value);
					this.SendPropertyChanging();
					this._maNhom = value;
					this.SendPropertyChanged("maNhom");
					this.OnmaNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenNhom", DbType="VarChar(50)")]
		public string tenNhom
		{
			get
			{
				return this._tenNhom;
			}
			set
			{
				if ((this._tenNhom != value))
				{
					this.OntenNhomChanging(value);
					this.SendPropertyChanging();
					this._tenNhom = value;
					this.SendPropertyChanged("tenNhom");
					this.OntenNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghiChu", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string ghiChu
		{
			get
			{
				return this._ghiChu;
			}
			set
			{
				if ((this._ghiChu != value))
				{
					this.OnghiChuChanging(value);
					this.SendPropertyChanging();
					this._ghiChu = value;
					this.SendPropertyChanged("ghiChu");
					this.OnghiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nhom_Nguoi_Dung_Khach_Hang", Storage="_Khach_Hangs", ThisKey="maNhom", OtherKey="maNhomNguoiDung")]
		public EntitySet<Khach_Hang> Khach_Hangs
		{
			get
			{
				return this._Khach_Hangs;
			}
			set
			{
				this._Khach_Hangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nhom_Nguoi_Dung_Phan_Quyen", Storage="_Phan_Quyens", ThisKey="maNhom", OtherKey="maNhomNguoiDung")]
		public EntitySet<Phan_Quyen> Phan_Quyens
		{
			get
			{
				return this._Phan_Quyens;
			}
			set
			{
				this._Phan_Quyens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Khach_Hangs(Khach_Hang entity)
		{
			this.SendPropertyChanging();
			entity.Nhom_Nguoi_Dung = this;
		}
		
		private void detach_Khach_Hangs(Khach_Hang entity)
		{
			this.SendPropertyChanging();
			entity.Nhom_Nguoi_Dung = null;
		}
		
		private void attach_Phan_Quyens(Phan_Quyen entity)
		{
			this.SendPropertyChanging();
			entity.Nhom_Nguoi_Dung = this;
		}
		
		private void detach_Phan_Quyens(Phan_Quyen entity)
		{
			this.SendPropertyChanging();
			entity.Nhom_Nguoi_Dung = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Phan_Quyen")]
	public partial class Phan_Quyen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maNhomNguoiDung;
		
		private int _maManHinh;
		
		private System.Nullable<bool> _coQuyen;
		
		private EntityRef<DM_Man_Hinh> _DM_Man_Hinh;
		
		private EntityRef<Nhom_Nguoi_Dung> _Nhom_Nguoi_Dung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaNhomNguoiDungChanging(int value);
    partial void OnmaNhomNguoiDungChanged();
    partial void OnmaManHinhChanging(int value);
    partial void OnmaManHinhChanged();
    partial void OncoQuyenChanging(System.Nullable<bool> value);
    partial void OncoQuyenChanged();
    #endregion
		
		public Phan_Quyen()
		{
			this._DM_Man_Hinh = default(EntityRef<DM_Man_Hinh>);
			this._Nhom_Nguoi_Dung = default(EntityRef<Nhom_Nguoi_Dung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhomNguoiDung", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int maNhomNguoiDung
		{
			get
			{
				return this._maNhomNguoiDung;
			}
			set
			{
				if ((this._maNhomNguoiDung != value))
				{
					if (this._Nhom_Nguoi_Dung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNhomNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._maNhomNguoiDung = value;
					this.SendPropertyChanged("maNhomNguoiDung");
					this.OnmaNhomNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maManHinh", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int maManHinh
		{
			get
			{
				return this._maManHinh;
			}
			set
			{
				if ((this._maManHinh != value))
				{
					if (this._DM_Man_Hinh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaManHinhChanging(value);
					this.SendPropertyChanging();
					this._maManHinh = value;
					this.SendPropertyChanged("maManHinh");
					this.OnmaManHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_coQuyen", DbType="Bit")]
		public System.Nullable<bool> coQuyen
		{
			get
			{
				return this._coQuyen;
			}
			set
			{
				if ((this._coQuyen != value))
				{
					this.OncoQuyenChanging(value);
					this.SendPropertyChanging();
					this._coQuyen = value;
					this.SendPropertyChanged("coQuyen");
					this.OncoQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DM_Man_Hinh_Phan_Quyen", Storage="_DM_Man_Hinh", ThisKey="maManHinh", OtherKey="maManHinh", IsForeignKey=true)]
		public DM_Man_Hinh DM_Man_Hinh
		{
			get
			{
				return this._DM_Man_Hinh.Entity;
			}
			set
			{
				DM_Man_Hinh previousValue = this._DM_Man_Hinh.Entity;
				if (((previousValue != value) 
							|| (this._DM_Man_Hinh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DM_Man_Hinh.Entity = null;
						previousValue.Phan_Quyens.Remove(this);
					}
					this._DM_Man_Hinh.Entity = value;
					if ((value != null))
					{
						value.Phan_Quyens.Add(this);
						this._maManHinh = value.maManHinh;
					}
					else
					{
						this._maManHinh = default(int);
					}
					this.SendPropertyChanged("DM_Man_Hinh");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nhom_Nguoi_Dung_Phan_Quyen", Storage="_Nhom_Nguoi_Dung", ThisKey="maNhomNguoiDung", OtherKey="maNhom", IsForeignKey=true)]
		public Nhom_Nguoi_Dung Nhom_Nguoi_Dung
		{
			get
			{
				return this._Nhom_Nguoi_Dung.Entity;
			}
			set
			{
				Nhom_Nguoi_Dung previousValue = this._Nhom_Nguoi_Dung.Entity;
				if (((previousValue != value) 
							|| (this._Nhom_Nguoi_Dung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Nhom_Nguoi_Dung.Entity = null;
						previousValue.Phan_Quyens.Remove(this);
					}
					this._Nhom_Nguoi_Dung.Entity = value;
					if ((value != null))
					{
						value.Phan_Quyens.Add(this);
						this._maNhomNguoiDung = value.maNhom;
					}
					else
					{
						this._maNhomNguoiDung = default(int);
					}
					this.SendPropertyChanged("Nhom_Nguoi_Dung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Phieu_Dat_Phong")]
	public partial class Phieu_Dat_Phong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maDatPhong;
		
		private System.Nullable<int> _maKH;
		
		private System.Nullable<int> _maPhong;
		
		private System.Nullable<System.DateTime> _checkIn;
		
		private System.Nullable<System.DateTime> _checkOut;
		
		private string _soTaiKhoan;
		
		private System.Nullable<decimal> _tongTien;
		
		private EntitySet<CT_PDP_DV> _CT_PDP_DVs;
		
		private EntityRef<Khach_Hang> _Khach_Hang;
		
		private EntityRef<Phong> _Phong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaDatPhongChanging(int value);
    partial void OnmaDatPhongChanged();
    partial void OnmaKHChanging(System.Nullable<int> value);
    partial void OnmaKHChanged();
    partial void OnmaPhongChanging(System.Nullable<int> value);
    partial void OnmaPhongChanged();
    partial void OncheckInChanging(System.Nullable<System.DateTime> value);
    partial void OncheckInChanged();
    partial void OncheckOutChanging(System.Nullable<System.DateTime> value);
    partial void OncheckOutChanged();
    partial void OnsoTaiKhoanChanging(string value);
    partial void OnsoTaiKhoanChanged();
    partial void OntongTienChanging(System.Nullable<decimal> value);
    partial void OntongTienChanged();
    #endregion
		
		public Phieu_Dat_Phong()
		{
			this._CT_PDP_DVs = new EntitySet<CT_PDP_DV>(new Action<CT_PDP_DV>(this.attach_CT_PDP_DVs), new Action<CT_PDP_DV>(this.detach_CT_PDP_DVs));
			this._Khach_Hang = default(EntityRef<Khach_Hang>);
			this._Phong = default(EntityRef<Phong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maDatPhong", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maDatPhong
		{
			get
			{
				return this._maDatPhong;
			}
			set
			{
				if ((this._maDatPhong != value))
				{
					this.OnmaDatPhongChanging(value);
					this.SendPropertyChanging();
					this._maDatPhong = value;
					this.SendPropertyChanged("maDatPhong");
					this.OnmaDatPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKH", DbType="Int")]
		public System.Nullable<int> maKH
		{
			get
			{
				return this._maKH;
			}
			set
			{
				if ((this._maKH != value))
				{
					if (this._Khach_Hang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaKHChanging(value);
					this.SendPropertyChanging();
					this._maKH = value;
					this.SendPropertyChanged("maKH");
					this.OnmaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maPhong", DbType="Int")]
		public System.Nullable<int> maPhong
		{
			get
			{
				return this._maPhong;
			}
			set
			{
				if ((this._maPhong != value))
				{
					if (this._Phong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaPhongChanging(value);
					this.SendPropertyChanging();
					this._maPhong = value;
					this.SendPropertyChanged("maPhong");
					this.OnmaPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_checkIn", DbType="Date")]
		public System.Nullable<System.DateTime> checkIn
		{
			get
			{
				return this._checkIn;
			}
			set
			{
				if ((this._checkIn != value))
				{
					this.OncheckInChanging(value);
					this.SendPropertyChanging();
					this._checkIn = value;
					this.SendPropertyChanged("checkIn");
					this.OncheckInChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_checkOut", DbType="Date")]
		public System.Nullable<System.DateTime> checkOut
		{
			get
			{
				return this._checkOut;
			}
			set
			{
				if ((this._checkOut != value))
				{
					this.OncheckOutChanging(value);
					this.SendPropertyChanging();
					this._checkOut = value;
					this.SendPropertyChanged("checkOut");
					this.OncheckOutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soTaiKhoan", DbType="VarChar(50)")]
		public string soTaiKhoan
		{
			get
			{
				return this._soTaiKhoan;
			}
			set
			{
				if ((this._soTaiKhoan != value))
				{
					this.OnsoTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._soTaiKhoan = value;
					this.SendPropertyChanged("soTaiKhoan");
					this.OnsoTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongTien", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> tongTien
		{
			get
			{
				return this._tongTien;
			}
			set
			{
				if ((this._tongTien != value))
				{
					this.OntongTienChanging(value);
					this.SendPropertyChanging();
					this._tongTien = value;
					this.SendPropertyChanged("tongTien");
					this.OntongTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phieu_Dat_Phong_CT_PDP_DV", Storage="_CT_PDP_DVs", ThisKey="maDatPhong", OtherKey="maDatPhong")]
		public EntitySet<CT_PDP_DV> CT_PDP_DVs
		{
			get
			{
				return this._CT_PDP_DVs;
			}
			set
			{
				this._CT_PDP_DVs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khach_Hang_Phieu_Dat_Phong", Storage="_Khach_Hang", ThisKey="maKH", OtherKey="maKH", IsForeignKey=true)]
		public Khach_Hang Khach_Hang
		{
			get
			{
				return this._Khach_Hang.Entity;
			}
			set
			{
				Khach_Hang previousValue = this._Khach_Hang.Entity;
				if (((previousValue != value) 
							|| (this._Khach_Hang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Khach_Hang.Entity = null;
						previousValue.Phieu_Dat_Phongs.Remove(this);
					}
					this._Khach_Hang.Entity = value;
					if ((value != null))
					{
						value.Phieu_Dat_Phongs.Add(this);
						this._maKH = value.maKH;
					}
					else
					{
						this._maKH = default(Nullable<int>);
					}
					this.SendPropertyChanged("Khach_Hang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phong_Phieu_Dat_Phong", Storage="_Phong", ThisKey="maPhong", OtherKey="maPhong", IsForeignKey=true)]
		public Phong Phong
		{
			get
			{
				return this._Phong.Entity;
			}
			set
			{
				Phong previousValue = this._Phong.Entity;
				if (((previousValue != value) 
							|| (this._Phong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Phong.Entity = null;
						previousValue.Phieu_Dat_Phongs.Remove(this);
					}
					this._Phong.Entity = value;
					if ((value != null))
					{
						value.Phieu_Dat_Phongs.Add(this);
						this._maPhong = value.maPhong;
					}
					else
					{
						this._maPhong = default(Nullable<int>);
					}
					this.SendPropertyChanged("Phong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CT_PDP_DVs(CT_PDP_DV entity)
		{
			this.SendPropertyChanging();
			entity.Phieu_Dat_Phong = this;
		}
		
		private void detach_CT_PDP_DVs(CT_PDP_DV entity)
		{
			this.SendPropertyChanging();
			entity.Phieu_Dat_Phong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Phong")]
	public partial class Phong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maPhong;
		
		private string _tenPhong;
		
		private System.Nullable<int> _soLuongNguoi;
		
		private System.Nullable<decimal> _donGia;
		
		private string _moTa;
		
		private System.Nullable<int> _maLoaiPhong;
		
		private System.Nullable<int> _trangThai;
		
		private EntitySet<Hinh_Anh_Phong> _Hinh_Anh_Phongs;
		
		private EntitySet<Phieu_Dat_Phong> _Phieu_Dat_Phongs;
		
		private EntityRef<Loai_Phong> _Loai_Phong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaPhongChanging(int value);
    partial void OnmaPhongChanged();
    partial void OntenPhongChanging(string value);
    partial void OntenPhongChanged();
    partial void OnsoLuongNguoiChanging(System.Nullable<int> value);
    partial void OnsoLuongNguoiChanged();
    partial void OndonGiaChanging(System.Nullable<decimal> value);
    partial void OndonGiaChanged();
    partial void OnmoTaChanging(string value);
    partial void OnmoTaChanged();
    partial void OnmaLoaiPhongChanging(System.Nullable<int> value);
    partial void OnmaLoaiPhongChanged();
    partial void OntrangThaiChanging(System.Nullable<int> value);
    partial void OntrangThaiChanged();
    #endregion
		
		public Phong()
		{
			this._Hinh_Anh_Phongs = new EntitySet<Hinh_Anh_Phong>(new Action<Hinh_Anh_Phong>(this.attach_Hinh_Anh_Phongs), new Action<Hinh_Anh_Phong>(this.detach_Hinh_Anh_Phongs));
			this._Phieu_Dat_Phongs = new EntitySet<Phieu_Dat_Phong>(new Action<Phieu_Dat_Phong>(this.attach_Phieu_Dat_Phongs), new Action<Phieu_Dat_Phong>(this.detach_Phieu_Dat_Phongs));
			this._Loai_Phong = default(EntityRef<Loai_Phong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maPhong", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maPhong
		{
			get
			{
				return this._maPhong;
			}
			set
			{
				if ((this._maPhong != value))
				{
					this.OnmaPhongChanging(value);
					this.SendPropertyChanging();
					this._maPhong = value;
					this.SendPropertyChanged("maPhong");
					this.OnmaPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenPhong", DbType="VarChar(100)")]
		public string tenPhong
		{
			get
			{
				return this._tenPhong;
			}
			set
			{
				if ((this._tenPhong != value))
				{
					this.OntenPhongChanging(value);
					this.SendPropertyChanging();
					this._tenPhong = value;
					this.SendPropertyChanged("tenPhong");
					this.OntenPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuongNguoi", DbType="Int")]
		public System.Nullable<int> soLuongNguoi
		{
			get
			{
				return this._soLuongNguoi;
			}
			set
			{
				if ((this._soLuongNguoi != value))
				{
					this.OnsoLuongNguoiChanging(value);
					this.SendPropertyChanging();
					this._soLuongNguoi = value;
					this.SendPropertyChanged("soLuongNguoi");
					this.OnsoLuongNguoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_donGia", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> donGia
		{
			get
			{
				return this._donGia;
			}
			set
			{
				if ((this._donGia != value))
				{
					this.OndonGiaChanging(value);
					this.SendPropertyChanging();
					this._donGia = value;
					this.SendPropertyChanged("donGia");
					this.OndonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_moTa", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string moTa
		{
			get
			{
				return this._moTa;
			}
			set
			{
				if ((this._moTa != value))
				{
					this.OnmoTaChanging(value);
					this.SendPropertyChanging();
					this._moTa = value;
					this.SendPropertyChanged("moTa");
					this.OnmoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLoaiPhong", DbType="Int")]
		public System.Nullable<int> maLoaiPhong
		{
			get
			{
				return this._maLoaiPhong;
			}
			set
			{
				if ((this._maLoaiPhong != value))
				{
					if (this._Loai_Phong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaLoaiPhongChanging(value);
					this.SendPropertyChanging();
					this._maLoaiPhong = value;
					this.SendPropertyChanged("maLoaiPhong");
					this.OnmaLoaiPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangThai", DbType="Int")]
		public System.Nullable<int> trangThai
		{
			get
			{
				return this._trangThai;
			}
			set
			{
				if ((this._trangThai != value))
				{
					this.OntrangThaiChanging(value);
					this.SendPropertyChanging();
					this._trangThai = value;
					this.SendPropertyChanged("trangThai");
					this.OntrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phong_Hinh_Anh_Phong", Storage="_Hinh_Anh_Phongs", ThisKey="maPhong", OtherKey="maPhong")]
		public EntitySet<Hinh_Anh_Phong> Hinh_Anh_Phongs
		{
			get
			{
				return this._Hinh_Anh_Phongs;
			}
			set
			{
				this._Hinh_Anh_Phongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phong_Phieu_Dat_Phong", Storage="_Phieu_Dat_Phongs", ThisKey="maPhong", OtherKey="maPhong")]
		public EntitySet<Phieu_Dat_Phong> Phieu_Dat_Phongs
		{
			get
			{
				return this._Phieu_Dat_Phongs;
			}
			set
			{
				this._Phieu_Dat_Phongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Loai_Phong_Phong", Storage="_Loai_Phong", ThisKey="maLoaiPhong", OtherKey="maLoaiPhong", IsForeignKey=true)]
		public Loai_Phong Loai_Phong
		{
			get
			{
				return this._Loai_Phong.Entity;
			}
			set
			{
				Loai_Phong previousValue = this._Loai_Phong.Entity;
				if (((previousValue != value) 
							|| (this._Loai_Phong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Loai_Phong.Entity = null;
						previousValue.Phongs.Remove(this);
					}
					this._Loai_Phong.Entity = value;
					if ((value != null))
					{
						value.Phongs.Add(this);
						this._maLoaiPhong = value.maLoaiPhong;
					}
					else
					{
						this._maLoaiPhong = default(Nullable<int>);
					}
					this.SendPropertyChanged("Loai_Phong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Hinh_Anh_Phongs(Hinh_Anh_Phong entity)
		{
			this.SendPropertyChanging();
			entity.Phong = this;
		}
		
		private void detach_Hinh_Anh_Phongs(Hinh_Anh_Phong entity)
		{
			this.SendPropertyChanging();
			entity.Phong = null;
		}
		
		private void attach_Phieu_Dat_Phongs(Phieu_Dat_Phong entity)
		{
			this.SendPropertyChanging();
			entity.Phong = this;
		}
		
		private void detach_Phieu_Dat_Phongs(Phieu_Dat_Phong entity)
		{
			this.SendPropertyChanging();
			entity.Phong = null;
		}
	}
}
#pragma warning restore 1591
